# Generated by Django 4.2.2 on 2023-06-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('date', models.IntegerField()),
                ('description', models.TextField(max_length=371)),
                ('played', models.TextField(max_length=371)),
            ],
        ),
    ]
