# Generated by Django 4.2.2 on 2023-06-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
