# Generated by Django 4.2.2 on 2023-06-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_guitar_for_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
